edition = "2021"
max_width = 132
use_field_init_shorthand = true
use_try_shorthand = true

#unstable_features = true
#fn_single_line = true
#format_code_in_doc_comments = true
#format_macro_matchers = true
#format_strings = true
#group_imports = "StdExternalCrate"
#hex_literal_case = "Upper"
#imports_layout = "HorizontalVertical"
#imports_granularity = "Module"
#reorder_impl_items = true
#version = "Two"
#wrap_comments = true
